# Generated by Django 2.2 on 2019-07-25 04:46

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='pics')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_desc', models.TextField()),
                ('banner_right_desc', models.TextField()),
                ('read_more_desc', models.TextField()),
            ],
            options={
                'db_table': 'vg_banner',
            },
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('country_code', models.CharField(max_length=6)),
                ('contact_email', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('insta_url', models.URLField()),
                ('linkedin_url', models.URLField()),
            ],
            options={
                'db_table': 'vg_contact_header',
            },
        ),
    ]
