# Generated by Django 2.2 on 2019-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190725_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionteam',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
