# Generated by Django 2.2 on 2019-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_professionteam_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=25)),
                ('avatar', models.ImageField(upload_to='media')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'vg_happy_clients',
            },
        ),
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_desc', models.TextField()),
                ('service_image', models.ImageField(upload_to='media')),
                ('service_icon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vg_service_offered',
            },
        ),
    ]
